create user brh
identified by brh
default tablespace users
quota unlimited on users

create table tb_departamento (
sigla varchar2(5) not null,
nome varchar2(50) not null,
chefe varchar2(50) not null,
departamento_superior varchar2(5)
)

create table tb_colaborador (
matricula varchar2(8) not null,
cpf char(14) not null,
nome varchar2(50) not null,
salario decimal(10,2) not null,
logradouro varchar2(150) not null,
complemento varchar2(30) not null,
cep varchar2(10) not null,
departamento varchar2(5) not null
)

create table tb_cep (
cep varchar2(10) not null,
bairro varchar2(50) not null,
cidade varchar2(50) not null,
estado varchar2(2) not null
)

create table tb_telefone_colaborador (
matricula varchar2(8) not null,
numero varchar2(14) not null,
tipo char(3) not null
)

create table tb_email_colaborador (
matricula varchar2(8) not null,
email varchar2(50) not null,
tipo char(3) not null
)

create table tb_dependentes (
cpf char(14) not null,
matricula_colaborador varchar2(8) not null,
nome varchar2(50) not null,
data_nascimento date not null,
parentesco varchar2(20) not null
)

create table tb_projetos (
id integer generated by default as identity (start with 1) not null,
nome varchar2(100) not null,
responsavel varchar2(8) not null,
inicio date not null,
fim date 
)

create table tb_atribuicao (
colaborador varchar2(8) not null,
projeto integer not null,
papel integer not null
)

create table tb_papel (
id integer generated by default as identity (start with 1) not null,
nome varchar2(100) not null
);


